package com.group6.malaware;

import android.content.SharedPreferences;
import android.content.res.ColorStateList;
import android.support.design.widget.FloatingActionButton;
import android.widget.TextView;

import java.util.Timer;
import java.util.TimerTask;

/**
 * Created by michaeldegraw on 11/24/15.
 */
public class IncreaseResource extends ActionSkill{
    public IncreaseResource(MainActivity activity, GameManager manager, SharedPreferences sharedPref, FloatingActionButton actionButton, TextView txt){
        super(activity, manager, sharedPref, actionButton, txt, "Increase Resource Generation",
                "This action skill will increase the amount of resource you passively generate for a short time",
                "Each upgrade to this action skill will increase the amount of resources generated by 50%", 10, 60, 20d);
    }

    @Override
    protected double getCostOfUpgradeLevel(int upgradeLevel) {
        return cost + (upgradeLevel * 100);
    }

    @Override
    public void activateEffect() {
        manager.tempIncreaseResourcesPerSec(manager.getResourcesPerSec(), 10000);
    }
}
